### ISSUE TITLE
token prefix in roberta model?

### ISSUE THREAD

**Issue by sarthusarth** [jalammar/ecco#73]
Trying to use a custom trained Roberta model by loading the config file but getting the error the token prefix is not present in the config. Any idea how to fix it?
<img width="1163" alt="Screenshot 2022-02-02 at 3 30 31 PM" src="https://user-images.githubusercontent.com/17705073/152175726-3c0d3ae5-52fe-4afa-b46b-5fb56b73f240.png">

**Comment by guustfranssensEY** [comment]
Is the token prefix specified in your config.json file?

**Comment by jalammar** [comment]
Yeah as @guustfranssensEY mentioned, make sure you have the prefix. This is an example from [model-config.yaml](https://github.com/jalammar/ecco/blob/main/src/ecco/model-config.yaml):

```
roberta-base:
    embedding: 'embeddings.word_embeddings'
    type: 'mlm'
    activations:
        - '\d+\.output\.dense'
    token_prefix: 'Ġ'
    partial_token_prefix: ''
```
